[application]

# App (Project) Name
name = "{{project-name}}"
# Dioxus App Default Platform
default_platform = "web"
# `build` & `serve` dist path
out_dir = "dist"
# resource (assets) file folder
asset_dir = "assets"

[bundle]
icon = ["/assets/banner.png"]

[web.app]

base_path = "/"
# HTML title tag content
title = "Happy birthday"

[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets"]

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
