name: Dioxus Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          profile: minimal
          target: wasm32-unknown-unknown
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Install Dioxus CLI
        run: cargo install dioxus-cli

      - name: Build Project ⚙️
        run: |
          dx bundle --release
          cp dist\public dist

      - name: Deploy Project 🚀
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: release
          folder: dist
          clean: false
          token: ${{ secrets.GH_TOKEN }}